name = "IncrementalInferenceTypes"
uuid = "9808408f-4dbc-47e4-913c-6068b950e289"
version = "0.1.0"
authors = ["Johannes Terblanche <Affie@users.noreply.github.com>"]

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
DistributedFactorGraphs = "b5cc3c7e-6572-11e9-2517-99fb8daf2f04"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
LieGroups = "6774de46-80ba-43f8-ba42-e41071ccfc5f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Manifolds = "1cead3c2-87b3-11e9-0ccd-23c62b72b94e"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StructTypes = "856f2bd8-1eba-4b0a-8007-ebc267875bd4"

[compat]
Dates = "1.10.0"
Distributed = "1.10.0"
DistributedFactorGraphs = "0.27, 0.28.0"
Distributions = "0.25.120"
DocStringExtensions = "0.9.5"
LieGroups = "0.1.2"
LinearAlgebra = "1.10.0"
Manifolds = "0.10.16, 0.11"
RecursiveArrayTools = "3.33.0"
StaticArrays = "1.9.13"
StructTypes = "1.11.0"
julia = "1.10"
