name: CI
on:
  pull_request:
  push:
    branches:
      - develop
      - release**
  workflow_dispatch:
  
jobs:
  test-stable:
    name: Stable JL-${{ matrix.version }} - ${{ matrix.group }}
    runs-on: ${{ matrix.os }}
    env:
      JULIA_PKG_SERVER: ""
    strategy:
      fail-fast: false
      matrix:
        version:
          - 'lts'
        os:
          - ubuntu-latest
        arch:
          - x64
        group:
          - 'basic_functional_group'
          - 'test_cases_group'
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/cache@v2
      - uses: julia-actions/julia-buildpkg@v1
      - name: Dev dependencies
        shell: julia --project=monorepo {0}
        run: |
          using Pkg;
          Pkg.develop([PackageSpec(path="IncrementalInference"), PackageSpec(path="IncrementalInferenceTypes")]);
      - name: Run tests
        continue-on-error: ${{ matrix.group == 'tmp_debug_group' }}
        env:
          IIF_TEST_GROUP: ${{ matrix.group }}
        run: >
          julia --color=yes --project=monorepo -e 'using Pkg; Pkg.test("IncrementalInference")'
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v2
        with:
          files: lcov.info
          fail_ci_if_error: false
        if: ${{ matrix.version != 'nightly' }}

  upstream-dev:
    name: Develop JL-${{ matrix.version }} - ${{ matrix.group }}
    runs-on: ubuntu-latest
    env: 
      JULIA_PKG_SERVER: ""
    strategy:
      fail-fast: false
      matrix:
        arch: 
          - x64
        version:
          - '1'
        group:
          - 'basic_functional_group'
          - 'test_cases_group'
          - 'tmp_debug_group'
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/cache@v2
      # - run: |
      #     git config --global user.name Tester
      #     git config --global user.email te@st.er
      - name: Dev dependencies
        shell: julia --project=monorepo {0}
        run: |
          using Pkg;
          Pkg.add(PackageSpec(name="DistributedFactorGraphs",rev="develop"))
          Pkg.add(PackageSpec(name="ApproxManifoldProducts",rev="develop"));
          Pkg.develop([PackageSpec(path="IncrementalInference"), PackageSpec(path="IncrementalInferenceTypes")]);
      - name: Run tests
        continue-on-error: ${{ matrix.group == 'tmp_debug_group' }}
        env:
          IIF_TEST_GROUP: ${{ matrix.group }}
        run: >
          julia --color=yes --project=monorepo -e 'using Pkg; Pkg.test("IncrementalInference")'
          